name: Package WAR

on:
  workflow_dispatch:
    inputs:
      war_version:
        description: 'version for war file'
        default: '1.5.2'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn package
      
      - name: Archive WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: guacamole-${{ inputs.war_version }}.war
          path: |
            guacamole/target/*.war
